import type { Metadata } from "next";
import { ebGaramondSans, interSans } from "./fonts";
import "./globals.css";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${interSans.variable} ${ebGaramondSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
              <Header />
        {children}
      </body>
    </html>
  );
}
